### ISSUE TITLE
Colab

### ISSUE THREAD

**Issue by jkss13** [ramidedantas/GCMS-2023-1#2]
@ramidedantas pode me incluir como colaboradora do seu repositório?

**Comment by jkss13** [comment]
@ramidedantas incluí meu nome no README do repositório da turma como colaboradora

**Comment by ramidedantas** [comment]
@jkss13 convite enviado.

**Comment by ramidedantas** [comment]
@jkss13 aceite o convite e faça a modificação no README como informado na prática.
