### ISSUE TITLE
Solicitação para colaboração

### ISSUE THREAD

**Issue by iagopedro** [ramidedantas/GCMS-2023-1#20]
Professor @ramidedantas , desejo ser um colaborador no projeto.

**Comment by iagopedro** [comment]
Realizei um commit com a inclusão do meu nome como colaborador no README.md.

**Comment by ramidedantas** [comment]
@iagopedro fiz o convite pro repositório. Você não deve conseguir comitar nele antes de aceitar.

**Comment by iagopedro** [comment]
Convite aceito.

**Comment by iagopedro** [comment]
Adicionei meu nome e usuário no README.

**Comment by ramidedantas** [comment]
ok @iagopedro, fechando issue.
