### ISSUE TITLE
Solicitação para colaborar no repositório

### ISSUE THREAD

**Issue by NicolasSilvaDA** [ramidedantas/GCMS-2023-1#3]
@ramidedantas Desejo contribuir para este repositório

**Comment by ramidedantas** [comment]
@NicolasSilvaDA convite enviado.

**Comment by NicolasSilvaDA** [comment]
@ramidedantas Update no Readme feito

**Comment by ramidedantas** [comment]
@NicolasSilvaDA OK, fechando issue.
