### ISSUE TITLE
Solicitação para ser colaborador do repositório.

### ISSUE THREAD

**Issue by scpaes** [ramidedantas/GCMS-2023-1#4]
@ramidedantas , issue solicitando para ser colaborador do repositório

**Comment by ramidedantas** [comment]
@scpaes convite enviado.

**Comment by scpaes** [comment]
@ramidedantas, readme atualizado. 

> @scpaes convite enviado.

**Comment by ramidedantas** [comment]
@scpaes OK, fechando issue.
