### ISSUE TITLE
Solicitação para ser colaborador - Rennan 

### ISSUE THREAD

**Issue by rennanprysthon** [ramidedantas/GCMS-2023-1#5]
@ramidedantas 

Solicito acesso para ser colaborador do repositório.

**Comment by ramidedantas** [comment]
@rennanprysthon convite enviado.

**Comment by rennanprysthon** [comment]
@ramidedantas 

Pull request criado: https://github.com/ramidedantas/GCMS-2023-1/pull/9

**Comment by ramidedantas** [comment]
@rennanprysthon não vamos fazer PR nessa prática, só mais a frente.
