### ISSUE TITLE
Solicitação para colaboração no Repositório 

### ISSUE THREAD

**Issue by MoonEye696** [ramidedantas/GCMS-2023-1#8]
@ramidedantas

**Comment by ramidedantas** [comment]
@MoonEye696 convite enviado.

**Comment by MoonEye696** [comment]
@ramidedantas O senhor pode enviar o convite novamente, acabei perdendo o prazo pra responder o convite segundo o github.

**Comment by ramidedantas** [comment]
@MoonEye696 enviei novamente.
